### ISSUE TITLE
Update online documentation

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamDocumentation#46]
Including Administrator Guide (non quick start part)  and Developer Guide

**Comment by loomis** [comment]
The Developer Guide has been largely rewritten focusing on how both our own developers and outsiders can checkout and build all of the SlipStream sources with a minimum of effort.  The most complicated aspects of this are related to the installation of the required dependencies on the underlying operating system.

**Comment by loomis** [comment]
The administrator guide needs to be rewritten following the steps given in the quick installation script.  I've removed all of the sections except the maintenance section and the cloud connector configuration.  An issue has been created for this: slipstream/SlipStreamDocumentation#50.
