### ISSUE TITLE
Add details of how to configure SlipStream for each cloud connector

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamDocumentation#51]
These informations can be found on old blog entries.

**Comment by loomis** [comment]
- [ ] add help text to connector parameters for the users
- [ ] add sections to installation/configuration guide

**Comment by schaubl** [comment]
- [ ] Update screenshots
- [ ] Check what to do with Pricing
- [ ] Check what to do with `config based` configuration since the button "Reload from config file doesn't exist anymore"

**Comment by schaubl** [comment]
The OCCI page is there but there is no link to it because it's not finished yet #62.

**Comment by schaubl** [comment]
I reopened this issue to put it into `Ready to validate` to remember me to present the changes into the next demo.
