### ISSUE TITLE
update and publish ReadTheDocs pages

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamDocumentation#70]
- [x] update the rtfd branch with changes since last conversion of source files
- [x] replace master branch with rtfd branch
- [x] build and publish documentation on the ReadTheDocs site from the master branch

**Comment by mebster** [comment]
Also update the sitemap. Created a simple Python script that will aggregate sitemaps from parts, which can be generated with tools like: https://pro-sitemaps.com
